# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_aihwmyhospitals_wrappers", use_symbols = TRUE, package_name = "aihwmyhospitals")

#' @usage NULL
#' @useDynLib aihwmyhospitals, .registration = TRUE
NULL

MyHospitalsClient <- new.env(parent = emptyenv())

MyHospitalsClient$new <- function(base_url) .Call(wrap__MyHospitalsClient__new, base_url)

MyHospitalsClient$get_caveats <- function() .Call(wrap__MyHospitalsClient__get_caveats, self)

MyHospitalsClient$get_caveat_by_code <- function(caveat_code) .Call(wrap__MyHospitalsClient__get_caveat_by_code, self, caveat_code)

MyHospitalsClient$get_suppressions <- function() .Call(wrap__MyHospitalsClient__get_suppressions, self)

MyHospitalsClient$get_suppression_by_code <- function(suppression_code) .Call(wrap__MyHospitalsClient__get_suppression_by_code, self, suppression_code)

MyHospitalsClient$get_datasets <- function(measure_code, reported_measure_code) .Call(wrap__MyHospitalsClient__get_datasets, self, measure_code, reported_measure_code)

MyHospitalsClient$get_dataset_by_id <- function(dataset_id) .Call(wrap__MyHospitalsClient__get_dataset_by_id, self, dataset_id)

MyHospitalsClient$get_dataset_data_items <- function(dataset_id) .Call(wrap__MyHospitalsClient__get_dataset_data_items, self, dataset_id)

MyHospitalsClient$get_measures <- function(measure_category_code) .Call(wrap__MyHospitalsClient__get_measures, self, measure_category_code)

MyHospitalsClient$get_measure_by_code <- function(measure_code) .Call(wrap__MyHospitalsClient__get_measure_by_code, self, measure_code)

MyHospitalsClient$get_measure_data_items <- function(measure_code) .Call(wrap__MyHospitalsClient__get_measure_data_items, self, measure_code)

MyHospitalsClient$get_measure_reporting_units_available <- function(measure_code) .Call(wrap__MyHospitalsClient__get_measure_reporting_units_available, self, measure_code)

MyHospitalsClient$get_measure_categories <- function() .Call(wrap__MyHospitalsClient__get_measure_categories, self)

MyHospitalsClient$get_measure_category_by_code <- function(measure_category_code) .Call(wrap__MyHospitalsClient__get_measure_category_by_code, self, measure_category_code)

MyHospitalsClient$get_measure_category_measures <- function(measure_category_code) .Call(wrap__MyHospitalsClient__get_measure_category_measures, self, measure_category_code)

MyHospitalsClient$get_reported_measures <- function(reported_measure_category_code) .Call(wrap__MyHospitalsClient__get_reported_measures, self, reported_measure_category_code)

MyHospitalsClient$get_reported_measure_by_code <- function(reported_measure_code) .Call(wrap__MyHospitalsClient__get_reported_measure_by_code, self, reported_measure_code)

MyHospitalsClient$get_reported_measure_data_items <- function(reported_measure_code) .Call(wrap__MyHospitalsClient__get_reported_measure_data_items, self, reported_measure_code)

MyHospitalsClient$get_reported_measure_categories <- function() .Call(wrap__MyHospitalsClient__get_reported_measure_categories, self)

MyHospitalsClient$get_reported_measure_category_by_code <- function(reported_measure_category_code) .Call(wrap__MyHospitalsClient__get_reported_measure_category_by_code, self, reported_measure_category_code)

MyHospitalsClient$get_reported_measure_category_reported_measures <- function(reported_measure_category_code) .Call(wrap__MyHospitalsClient__get_reported_measure_category_reported_measures, self, reported_measure_category_code)

MyHospitalsClient$get_reporting_units <- function(reporting_unit_type_code) .Call(wrap__MyHospitalsClient__get_reporting_units, self, reporting_unit_type_code)

MyHospitalsClient$get_reporting_unit_by_code <- function(reporting_unit_code) .Call(wrap__MyHospitalsClient__get_reporting_unit_by_code, self, reporting_unit_code)

MyHospitalsClient$get_reporting_unit_data_items <- function(reporting_unit_code) .Call(wrap__MyHospitalsClient__get_reporting_unit_data_items, self, reporting_unit_code)

MyHospitalsClient$get_reporting_unit_measures_available <- function(reporting_unit_code) .Call(wrap__MyHospitalsClient__get_reporting_unit_measures_available, self, reporting_unit_code)

MyHospitalsClient$get_reporting_unit_bricks_available <- function(reporting_unit_code) .Call(wrap__MyHospitalsClient__get_reporting_unit_bricks_available, self, reporting_unit_code)

MyHospitalsClient$get_reporting_unit_types <- function() .Call(wrap__MyHospitalsClient__get_reporting_unit_types, self)

MyHospitalsClient$get_reporting_unit_type_by_code <- function(reporting_unit_type_code) .Call(wrap__MyHospitalsClient__get_reporting_unit_type_by_code, self, reporting_unit_type_code)

MyHospitalsClient$get_reporting_unit_type_bricks_available <- function(reporting_unit_type_code) .Call(wrap__MyHospitalsClient__get_reporting_unit_type_bricks_available, self, reporting_unit_type_code)

MyHospitalsClient$get_flat_data_extract <- function(measure_category_code, skip, top, reporting_unit_type_code, measure_code, reporting_unit_code, start_date, end_date) .Call(wrap__MyHospitalsClient__get_flat_data_extract, self, measure_category_code, skip, top, reporting_unit_type_code, measure_code, reporting_unit_code, start_date, end_date)

MyHospitalsClient$get_flat_formatted_data_extract <- function(measure_category_code, skip, top, reporting_unit_type_code, measure_code, reporting_unit_code, start_date, end_date) .Call(wrap__MyHospitalsClient__get_flat_formatted_data_extract, self, measure_category_code, skip, top, reporting_unit_type_code, measure_code, reporting_unit_code, start_date, end_date)

MyHospitalsClient$get_simple_download_codes <- function() .Call(wrap__MyHospitalsClient__get_simple_download_codes, self)

MyHospitalsClient$download_simple <- function(download_code) .Call(wrap__MyHospitalsClient__download_simple, self, download_code)

MyHospitalsClient$get_measure_download_codes <- function() .Call(wrap__MyHospitalsClient__get_measure_download_codes, self)

MyHospitalsClient$download_measure <- function(measure_download_code) .Call(wrap__MyHospitalsClient__download_measure, self, measure_download_code)

MyHospitalsClient$download_measure_across_reporting_units <- function(measure_download_code) .Call(wrap__MyHospitalsClient__download_measure_across_reporting_units, self, measure_download_code)

MyHospitalsClient$get_reporting_unit_datasheet_codes <- function() .Call(wrap__MyHospitalsClient__get_reporting_unit_datasheet_codes, self)

MyHospitalsClient$download_reporting_unit_datasheet <- function(datasheet_code, reporting_unit_code) .Call(wrap__MyHospitalsClient__download_reporting_unit_datasheet, self, datasheet_code, reporting_unit_code)

#' @export
`$.MyHospitalsClient` <- function (self, name) { func <- MyHospitalsClient[[name]]; environment(func) <- environment(); func }

#' @export
`[[.MyHospitalsClient` <- `$.MyHospitalsClient`


# nolint end
